### PR TITLE
Fixed issues around the spacing of text expand buttons

### PR DESCRIPTION
**Pull request by Blackbaud-TrevorBurch**
#35 & #36

### CODE REVIEW

**Comment by Blackbaud-AlexKingman** [comment]
@Blackbaud-TrevorBurch See this screenshot of how the expand buttons look using node `v6.17.0`:
Screen Shot 2019-05-28 at 9 24 20 AM

Before your change, the spacing was `5px` for "See less" and `12px` for "See more". Now they are `10px` and `14px` respectively. Is this deliberate?

**Comment by Blackbaud-TrevorBurch** [comment]
@Blackbaud-AlexKingman was one of those Sky 2 vs Sky 3? It will have slightly more spacing on Sky 2 due to the whitespace issue. 

The 10px for the "See Less" is correct. However, on Sky 2 you will see 14px on Sky 2 because there is an end of file whitespace character that is rendered. In Sky 3 that is no longer rendered and it will also be 10px.

**Comment by Blackbaud-AlexKingman** [comment]
@Blackbaud-TrevorBurch These samples were all just straight from the library's visual demo.

**Comment by Blackbaud-TrevorBurch** [comment]
Yup. The visual demo is still on Sky 2 and thus will show the extra space. Sky 3 will not.

**Pull request merged**
