### PR TITLE
Add deprecation note to definition list

### PR DESCRIPTION
**Pull request by blackbaud-johnly**

### CODE REVIEW

**Comment by blackbaud-ado** [comment]
Preview build at [https://developer.blackbaud.com/skyux-layout?_sp.spa=pr-deprecate-definition-list](https://developer.blackbaud.com/skyux-layout?_sp.spa=pr-deprecate-definition-list)

**Comment by Blackbaud-AdamFunderburk** [comment]
Is the precedent for this scenario to use an "info" type of alert to display the deprecation message? It seems like the type of content that might warrant a "warning" type.

**Comment by blackbaud-johnly** [comment]
@Blackbaud-AdamFunderburk, I don't think we have a set pattern, but it looks like we've used warnings in the past for release-candidate components that are subject to change. Seems like this is similar enough to follow that pattern. ... My only hesitation is that the component isn't currently deprecated. It's just slated for deprecation in the next major version of SKY UX. Not sure if that distinction takes this from "warning" to "info," so I'll go ahead and change this to a warning. But let me know you think the distinction makes a difference.

**Comment by blackbaud-ado** [comment]
Preview build at [https://developer.blackbaud.com/skyux-layout?_sp.spa=pr-deprecate-definition-list](https://developer.blackbaud.com/skyux-layout?_sp.spa=pr-deprecate-definition-list)

**Comment by blackbaud-ado** [comment]
Preview build at [https://developer.blackbaud.com/skyux-layout?_sp.spa=pr-deprecate-definition-list](https://developer.blackbaud.com/skyux-layout?_sp.spa=pr-deprecate-definition-list)

**Review by Blackbaud-AlexKingman — APPROVED** [review]

**Pull request merged**
