### PR TITLE
Release 4.6.0

### PR DESCRIPTION
**Pull request by johnhwhite**

### CODE REVIEW

**Review by blackbaud-paulah — APPROVED** [review]

**Review by Blackbaud-TrevorBurch — CHANGES_REQUESTED** [review]
@johnhwhite - shouldn't we also be updating the `package-lock.json` since it includes the version number?

**Comment by blackbaud-ado** [comment]
Preview build at [https://developer.blackbaud.com/skyux-layout?_sp.spa=pr-release-4.6.0](https://developer.blackbaud.com/skyux-layout?_sp.spa=pr-release-4.6.0)

**Comment by johnhwhite** [comment]
> @johnhwhite - shouldn't we also be updating the `package-lock.json` since it includes the version number?

Good catch, updated.

**Review by blackbaud-paulah — APPROVED** [review]

**Review by Blackbaud-TrevorBurch — APPROVED** [review]

**Comment by blackbaud-ado** [comment]
Preview build at [https://developer.blackbaud.com/skyux-layout?_sp.spa=pr-release-4.6.0](https://developer.blackbaud.com/skyux-layout?_sp.spa=pr-release-4.6.0)

**Pull request merged**
