### PR TITLE
Got rid of overflow causing odd outline

### PR DESCRIPTION
**Pull request by Blackbaud-AdamSc**
This gets rid of the overflow when the buttons have the issue.  Doesn't affect content and keeps the browsers default outline styling.

### CODE REVIEW

**Comment by Blackbaud-AdamSc** [comment]
@skyux-team

**Comment by Blackbaud-AdamSc** [comment]
Not sure on the Access Denied error that caused this to fail.  Something you see sometimes? retry?

**Comment by Blackbaud-BobbyEarl** [comment]
That error makes sense as the Browserstack credentials aren't available on PRs from forks. I'll report back with a solution soon.

**Comment by Blackbaud-BobbyEarl** [comment]
Preview build at [https://host.nxt.blackbaud.com/skyux-layout?_sp.spa=pr-adam-fix-button-outline](https://host.nxt.blackbaud.com/skyux-layout?_sp.spa=pr-adam-fix-button-outline)

**Comment by Blackbaud-SteveBrush** [comment]
To avoid using `overflow`, I refactored the action button to use flexbox.
See: https://github.com/blackbaud/skyux-layout/pull/64

**Pull request closed without merging**
